#
# Usage:
#	Make_Lib(<LIB_NAME> <LIB_TYPE> [<FILE1> ...])
#
MACRO(MAKE_LIB LIB_NAME LIB_TYPE)
	PROJECT(${LIB_NAME})
	IF(LIB_TYPE STREQUAL "SHARED")
		STRING(TOUPPER ${LIB_NAME} UPPER_LIB_NAME)
		ADD_DEFINITIONS(-D${UPPER_LIB_NAME}_AS_DLL)
		ADD_DEFINITIONS(-D${UPPER_LIB_NAME}_EXPORT)
	ENDIF()

	SET(CMAKE_OSX_SYSROOT "iphoneos")
	SET(MACOSX_BUNDLE_BUNDLE_NAME ${LIB_NAME})
	SET(CMAKE_XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY "1,2")
	SET(CMAKE_XCODE_ATTRIBUTE_SKIP_INSTALL "NO")
	ADD_LIBRARY(${LIB_NAME} STATIC ${ARGN})
	SET_TARGET_PROPERTIES(${LIB_NAME} PROPERTIES
		XCODE_ATTRIBUTE_VALIDATE_PRODUCT "YES"
		XCODE_ATTRIBUTE_COMBINE_HIDPI_IMAGES "NO"
		XCODE_ATTRIBUTE_INSTALL_PATH "$(LOCAL_LIBRARY_DIR)")

	IF(CMAKE_WIN_PLATFORM)
		ADD_DEFINITIONS(-WE4715)
		ADD_DEFINITIONS(-ZM200)
		ADD_LIBRARY(${LIB_NAME} ${LIB_TYPE} ${ARGN})
	ELSEIF(CMAKE_IOS_PLATFORM)
		SET(CMAKE_OSX_SYSROOT "IPHONEOS")
		SET(MACOSX_BUNDLE_BUNDLE_NAME ${EXE_NAME})
		SET(CMAKE_XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY "1,2")
		SET(CMAKE_XCODE_ATTRIBUTE_SKIP_INSTALL "NO")
		ADD_LIBRARY(${LIB_NAME} STATIC ${ARGN})
		SET_TARGET_PROPERTIES(${LIB_NAME} PROPERTIES
			XCODE_ATTRIBUTE_VALIDATE_PRODUCT "YES"
			XCODE_ATTRIBUTE_COMBINE_HIDPI_IMAGES "NO"
			XCODE_ATTRIBUTE_INSTALL_PATH "$(LOCAL_LIBRARY_DIR)")
	ENDIF()
ENDMACRO()
