#
# Usage:
#	Cmd_Cp(<SOURCE> <DESTINATION>)
#
FUNCTION(CMD_CP SOURCE DESTINATION)
	ABSOLUTE_PATH(SOURCE DESTINATION)
	IF(EXISTS ${SOURCE})
		IF((NOT IS_DIRECTORY ${SOURCE}) AND (IS_DIRECTORY ${DESTINATION}))
			FILE(COPY ${SOURCE} DESTINATION ${DESTINATION} 
				 PATTERN "*[.]svn" EXCLUDE 
				 PATTERN "*[.]git" EXCLUDE 
				 PATTERN "[.]DS_Store" EXCLUDE)
		ELSEIF((NOT EXISTS ${DESTINATION}) OR (NOT IS_DIRECTORY ${DESTINATION}))
			GET_FILENAME_COMPONENT(SOURCE_NAME ${SOURCE} NAME)
			GET_FILENAME_COMPONENT(DESTINATION_PATH ${DESTINATION} PATH)
			GET_FILENAME_COMPONENT(DESTINATION_NAME ${DESTINATION} NAME)
			FILE(COPY ${SOURCE} DESTINATION ${DESTINATION_PATH}/${SOURCE_NAME}-${PARAM_SUFFIX}
				 PATTERN "*[.]svn" EXCLUDE 
				 PATTERN "*[.]git" EXCLUDE 
				 PATTERN "[.]DS_Store" EXCLUDE)
			CMD_MV(${DESTINATION_PATH}/${SOURCE_NAME}-${PARAM_SUFFIX}/${SOURCE_NAME} ${DESTINATION})
			CMD_RM(${DESTINATION_PATH}/${SOURCE_NAME}-${PARAM_SUFFIX})
		ELSE()
			FILE(GLOB SUB_SOURCES ${SOURCE}/*)
			FOREACH(SUB_SOURCE ${SUB_SOURCES})
				GET_FILENAME_COMPONENT(SUB_SOURCE_NAME ${SUB_SOURCE} NAME)
				CMD_CP(${SUB_SOURCE} ${DESTINATION}/${SUB_SOURCE_NAME})
			ENDFOREACH()
		ENDIF()
	ELSEIF(${SOURCE} MATCHES "[*|?]")
		FILE(GLOB_RECURSE SUB_SOURCES ${SOURCE})
		IF(SUB_SOURCES)
			GET_FILENAME_COMPONENT(SOURCE_PATH ${SOURCE} PATH)
			STRING(LENGTH ${SOURCE_PATH} SOURCE_PATH_LENGTH)
			FOREACH(SUB_SOURCE ${SUB_SOURCES})
				GET_FILENAME_COMPONENT(SUB_SOURCE_PATH ${SUB_SOURCE} PATH)
				STRING(SUBSTRING ${SUB_SOURCE_PATH} ${SOURCE_PATH_LENGTH} -1 SUB_SOURCE_PATH_SUBSTRING)
				FILE(COPY ${SUB_SOURCE} DESTINATION ${DESTINATION}${SUB_SOURCE_PATH_SUBSTRING})
			ENDFOREACH()
		ENDIF()
	ENDIF()
ENDFUNCTION()
