#
# Usage:
#	Cmd_Rm(<SOURCE>)
#
FUNCTION(CMD_RM SOURCE)
	ABSOLUTE_PATH(SOURCE)
	IF(EXISTS ${SOURCE})
		IF(IS_DIRECTORY ${SOURCE})
			FILE(REMOVE_RECURSE ${SOURCE})
		ELSE()
			FILE(REMOVE ${SOURCE})
		ENDIF()
	ELSEIF(${SOURCE} MATCHES "[*|?]")
		FILE(GLOB_RECURSE SUB_SOURCES ${SOURCE})
		FOREACH(SUB_SOURCE ${SUB_SOURCES})
			FILE(REMOVE ${SUB_SOURCE})
		ENDFOREACH()
	ENDIF()
ENDFUNCTION()
