#
# Usage:
#	Cmd_Read(<SOURCE> <VALUE>)
#
FUNCTION(CMD_READ SOURCE VALUE)
	ABSOLUTE_PATH(SOURCE)
	SET(SOURCE_VALUE)
	IF((EXISTS ${SOURCE}) AND (NOT IS_DIRECTORY ${SOURCE}))
		FILE(READ ${SOURCE} SOURCE_VALUE)
	ENDIF()
	SET(${VALUE} ${SOURCE_VALUE} PARENT_SCOPE)
ENDFUNCTION()
