#
# Usage:
#	Cmd_Tar(<SOURCE> <DIRECTORY>)
#
FUNCTION(CMD_TAR SOURCE DIRECTORY)
	ABSOLUTE_PATH(SOURCE DIRECTORY)
	IF(IS_DIRECTORY ${DIRECTORY})
		EXECUTE_CMD(CMAKE -E tar xvf ${SOURCE} PATH ${DIRECTORY})
	ENDIF()
ENDFUNCTION()
