#
# Usage:
#	Cmd_Write(<SOURCE> <VALUE> [CREATE])
#
FUNCTION(CMD_WRITE SOURCE VALUE)
	ABSOLUTE_PATH(SOURCE)
	SET(PARAM_LIST CREATE)
	PARAM_PARSE(PARAM_LIST ${ARGN})
	IF((EXISTS ${SOURCE}) OR CREATE-FOUND)
		FILE(WRITE ${SOURCE} ${VALUE})
	ENDIF()
ENDFUNCTION()
