#
# Usage:
#	cmd_parse(<params> [ARGN])
#
if(cmd_parse_uid)
	string(RANDOM cmd_parse_uid)
endif()
function(cmd_parse ${cmd_parse_uid}_params)
	foreach(param ${${${cmd_parse_uid}_params}})
		set(param_value)
		set(param_found false)
		foreach(arg ${ARGN})
			if(${arg} STREQUAL ${param})
				set(param_found true)
			elseif(param_found)
				list(FIND ${${cmd_parse_uid}_params} ${arg} arg_position)
				if(${arg_position} EQUAL -1)
					list(APPEND param_value ${arg})
				else()
					break()
				endif()
			endif()
		endforeach()
		set(${param} ${param_value} PARENT_SCOPE)
		set(${param}-FOUND ${param_found} PARENT_SCOPE)
	endforeach()
endfunction()
