#
# Usage:
#	cmd_ls(<directory> <contents> [FILE|FOLDER])
#
function(cmd_ls directory contents)
	cmd_absolute(directory)
	set(content_list)
	set(sub_sources)
	if(IS_DIRECTORY ${directory})
		file(GLOB sub_sources ${directory}/*)
	elseif(${directory} MATCHES "[*|?]")
		file(GLOB sub_sources ${directory})
	endif()
	set(parse_params FILE FOLDER)
	cmd_parse(parse_params ${ARGN})
	if(FILE-FOUND)
		foreach(sub_source ${sub_sources})
			if(NOT IS_DIRECTORY ${sub_source})
				list(APPEND content_list ${sub_source})
			endif()
		endforeach()
	elseif(FOLDER-FOUND)
		foreach(sub_source ${sub_sources})
			if(IS_DIRECTORY ${sub_source})
				list(APPEND content_list ${sub_source})
			endif()
		endforeach()
	else()
		list(APPEND content_list ${sub_sources})
	endif()
	set(${contents} ${content_list} PARENT_SCOPE)
endfunction()
