
set(CMAKE_CXX_FLAGS "-std=gnu++98 -stdlib=libc++" CACHE STRING "CXX flags." FORCE)
set(CMAKE_EXE_LINKER_FLAGS "-stdlib=libc++ -ObjC" CACHE STRING "EXE linker flags." FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "-stdlib=libc++" CACHE STRING "Shared linker flags." FORCE)
set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++" CACHE STRING "CXX library." FORCE)
set(CMAKE_XCODE_ATTRIBUTE_GCC_C_LANGUAGE_STANDARD "gnu99" CACHE STRING "C Language standaed." FORCE)
set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "gnu++98" CACHE STRING "CXX Language standaed." FORCE)
