#
# Define unique Param_Prefix
# Define unique Param_Suffix
#
MACRO(DEFINE_PARAM SIGN)
	IF(DEFINED PARAM_${SIGN})
		UNSET(PARAM_${SIGN})
	ENDIF()
	STRING(RANDOM PARAM_${SIGN})
ENDMACRO()

DEFINE_PARAM(PREFIX)
DEFINE_PARAM(SUFFIX)
