#
# Usage:
#	Absolute_Path([<PATH> ...])
#
FUNCTION(ABSOLUTE_PATH)
	FOREACH(${PARAM_PREFIX}_DIRECTORY ${ARGN})
		GET_FILENAME_COMPONENT(ABSOLUTE_DIRECTORY ${${${PARAM_PREFIX}_DIRECTORY}} ABSOLUTE)
		SET(${${PARAM_PREFIX}_DIRECTORY} ${ABSOLUTE_DIRECTORY} PARENT_SCOPE)
	ENDFOREACH()
ENDFUNCTION()
