#
# Usage:
#	Execute_Cmd(<CMD> [<ARGS>]
#	                  [PATH <PATH>] 
#	                  [RESULT <RESULT>]
#	                  [OUTPUT <OUTPUT>])
#
FUNCTION(EXECUTE_CMD CMD)
	SET(PARAM_LIST PATH RESULT OUTPUT)
	PARAM_PARSE(PARAM_LIST ${ARGN})
	SET(RESULT_VALUE)
	SET(OUTPUT_VALUE)
	IF(PATH-FOUND)
		ABSOLUTE_PATH(PATH)
		EXECUTE_PROCESS(COMMAND ${CMD} ${PARAM_LIST-ARGS}
						WORKING_DIRECTORY ${PATH}
						RESULT_VARIABLE RESULT_VALUE
						OUTPUT_VARIABLE OUTPUT_VALUE)
	ELSE()
		EXECUTE_PROCESS(COMMAND ${CMD} ${PARAM_LIST-ARGS}
						RESULT_VARIABLE RESULT_VALUE
						OUTPUT_VARIABLE OUTPUT_VALUE)
	ENDIF()
	IF(RESULT-FOUND)
		SET(${RESULT} ${RESULT_VALUE} PARENT_SCOPE)
	ENDIF()
	IF(OUTPUT-FOUND)
		SET(${OUTPUT} ${OUTPUT_VALUE} PARENT_SCOPE)
	ENDIF()
ENDFUNCTION()
